const mongoose = require("mongoose");

const CourseSchema = new mongoose.Schema({
  title: { type: String, required: true },
  description: { type: String, required: true },
  instructor: { type: String, required: true },
  topicsCovered: { type: [String], required: true },
  prerequisites: { type: [String], required: true },
  targetAudience: { type: String, required: true },
  difficulty: { type: String, required: true },
  estimatedTimeToComplete: { type: String, required: true },
  certificationOptions: { type: [String] },
  courseObjectives: { type: [String], required: true },
  courseOutline: { type: [String], required: true },
  lectureContent: { type: [String], required: true },
  quizzesAndAssessments: { type: [String] },
  interactiveElements: { type: [String] },
  relatedResources: { type: [String] },
  discussionForums: { type: Boolean, default: false },
  userReviews: [{ type: mongoose.Schema.Types.ObjectId, ref: "Review" }],
  userRatings: [{ type: Number }],
  userFeedback: { type: String },
  socialMediaSharingOptions: { type: Boolean, default: false },
  videoTutorials: { type: [String] },
  audioTutorials: { type: [String] },
  infographics: { type: [String] },
  downloads: { type: [String] },
  affiliateMarketingOptions: { type: Boolean, default: false },
  promotionalMaterials: { type: [String] },
  courseFees: { type: Number, default: 0 },
  paymentOptions: { type: [String], default: [] },
  courseUpdatesAndVersionControl: { type: String },
  userProgressTrackingAndReporting: { type: Boolean, default: false },
  courseFormat: { type: String },
  languageOptions: { type: [String], default: [] },
  accessibilityOptions: { type: String },
  mobileCompatibility: { type: Boolean, default: false },
  courseRecommendations: { type: [String] },
  collaborativeLearningOptions: { type: Boolean, default: false },
  gamificationElements: { type: Boolean, default: false },
  personalizedLearningPaths: { type: Boolean, default: false },
  adaptiveLearningAlgorithms: { type: Boolean, default: false },
  artificialIntelligenceTutors: { type: Boolean, default: false },
  realTimeAnalyticsAndReporting: { type: Boolean, default: false },
  integrationWithOtherLearningManagementSystems: {
    type: Boolean,
    default: false,
  },
  openSourceCodeAvailability: { type: Boolean, default: false },
  integrationWithOtherEducationalTechnologies: {
    type: Boolean,
    default: false,
  },
  integrationWithJobMarketAndCareerDevelopmentResources: {
    type: Boolean,
    default: false,
  },
  integrationWithFinancialAidAndScholarshipOptions: {
    type: Boolean,
    default: false,
  },
  integrationWithSocialAndNetworkingPlatforms: {
    type: Boolean,
    default: false,
  },
  multiPlatformSupport: { type: Boolean, default: false },
  internationalizationAndLocalizationOptions: { type: Boolean, default: false },
  userDataPrivacyAndSecurityOptions: { type: Boolean, default: false },
  learningDataAnalyticsAndReporting: { type: Boolean, default: false },
  courseCompletionTrackingAndCertificationOptions: {
    type: Boolean,
    default: false,
  },
  collaborationWithUniversitiesAndAcademicInstitutions: {
    type: Boolean,
    default: false,
  },
  communityInvolvementAndEngagementOptions: { type: Boolean, default: false },
  accessibilityOptionsForIndividualsWithDisabilities: {
    type: Boolean,
    default: false,
  },
  translationOptionsForNonNativeSpeakers: { type: Boolean, default: false },
  integrationWithOtherLearningManagementSystems: {
    type: Boolean,
    default: false,
  },
  openSourceCodeAvailability: { type: Boolean, default: false },
  integrationWithOtherEducationalTechnologies: {
    type: Boolean,
    default: false,
  },
  integrationWithJobMarketAndCareerDevelopmentResources: {
    type: Boolean,
    default: false,
  },
  integrationWithFinancialAidAndScholarshipOptions: {
    type: Boolean,
    default: false,
  },
  integrationWithSocialAndNetworkingPlatforms: {
    type: Boolean,
    default: false,
  },
  multiPlatformSupport: { type: Boolean, default: false },
  internationalizationAndLocalizationOptions: { type: Boolean, default: false },
  userDataPrivacyAndSecurityOptions: { type: Boolean, default: false },
  learningDataAnalyticsAndReporting: { type: Boolean, default: false },
  courseCompletionTrackingAndCertificationOptions: {
    type: Boolean,
    default: false,
  },
  virtualClassrooms: { type: Boolean, default: false },
  liveSessions: { type: Boolean, default: false },
  groupProjects: { type: Boolean, default: false },
  peerReviews: { type: Boolean, default: false },
  badgesAndRecognition: { type: Boolean, default: false },
  analyticsAndDataTracking: { type: Boolean, default: false },
  customizableTemplates: { type: Boolean, default: false },
  userEngagementAndInteractionMetrics: { type: Boolean, default: false },
  aiTutorsAndEducationalAssistants: { type: Boolean, default: false },
  virtualAndAugmentedRealityLearningExperiences: {
    type: Boolean,
    default: false,
  },
  ecommerceSystemsIntegration: { type: Boolean, default: false },
  instructorMonetization: { type: Boolean, default: false },
  institutionLicensing: { type: Boolean, default: false },
  libraryAndDatabaseIntegration: { type: Boolean, default: false },
  customPlaylistsAndLearningPaths: { type: Boolean, default: false },
  scholarshipsAndFinancialAssistance: { type: Boolean, default: false },
  accreditationOptions: { type: Boolean, default: false },
  alumniAndPeersNetworking: { type: Boolean, default: false },
  jobSearchAndCareerDevelopmentTools: { type: Boolean, default: false },
  potentialEmployersAndInternships: { type: Boolean, default: false },
  webinarsAndEvents: { type: Boolean, default: false },
  onlineCommunitiesAndForums: { type: Boolean, default: false },
  individualCoachingAndMentorship: { type: Boolean, default: false },
  personalizedFeedbackAndProgressReports: { type: Boolean, default: false },
});

module.exports = mongoose.model("Course", CourseSchema);
